[build]
  command = "pnpm build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://crea-tu-horario-api.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200